[package]
name = "exes"
version = "0.0.1"
authors = ["Matthias Gilch <matthias.gilch.mg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.6"
